# version: "3.9" # optional since v1.27.0

name: microservice

services:
  customer-service:
    build: ./customer-service
    volumes:
      - ./customer-service/customer_service/db.sqlite3:/app/db.sqlite3
    environment:
      - CART_SERVICE_URL=http://cart-service:8888
    depends_on:
      - cart-service

  book-service:
    build: ./book-service
    volumes:
      - ./book-service/book_service/db.sqlite3:/app/db.sqlite3

  cart-service:
    build: ./cart-service
    volumes:
      - ./cart-service/cart_service/db.sqlite3:/app/db.sqlite3
    environment:
      - BOOK_SERVICE_URL=http://book-service:8888
    depends_on:
      - book-service

  staff-service:
    build: ./staff-service
    volumes:
      - ./staff-service/staff_service/db.sqlite3:/app/db.sqlite3

  manager-service:
    build: ./manager-service
    volumes:
      - ./manager-service/manager_service/db.sqlite3:/app/db.sqlite3

  catalog-service:
    build: ./catalog-service
    volumes:
      - ./catalog-service/catalog_service/db.sqlite3:/app/db.sqlite3

  order-service:
    build: ./order-service
    volumes:
      - ./order-service/order_service/db.sqlite3:/app/db.sqlite3
    environment:
      - PAY_SERVICE_URL=http://pay-service:8888
      - SHIP_SERVICE_URL=http://ship-service:8888
    depends_on:
      - pay-service
      - ship-service

  ship-service:
    build: ./ship-service
    volumes:
      - ./ship-service/ship_service/db.sqlite3:/app/db.sqlite3

  pay-service:
    build: ./pay-service
    volumes:
      - ./pay-service/pay_service/db.sqlite3:/app/db.sqlite3

  comment-rate-service:
    build: ./comment-rate-service
    volumes:
      - ./comment-rate-service/comment_rate_service/db.sqlite3:/app/db.sqlite3

  recommender-ai-service:
    build: ./recommender-ai-service
    volumes:
      - ./recommender-ai-service/recommender_ai_service/db.sqlite3:/app/db.sqlite3
    environment:
      - BOOK_SERVICE_URL=http://book-service:8888
      - COMMENT_RATE_SERVICE_URL=http://comment-rate-service:8888
    depends_on:
      - book-service
      - comment-rate-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8888:8888"
    volumes:
      - ./api-gateway/api_gateway/db.sqlite3:/app/db.sqlite3
    environment:
      - CUSTOMER_SERVICE_URL=http://customer-service:8888
      - BOOK_SERVICE_URL=http://book-service:8888
      - CART_SERVICE_URL=http://cart-service:8888
      - STAFF_SERVICE_URL=http://staff-service:8888
      - MANAGER_SERVICE_URL=http://manager-service:8888
      - CATALOG_SERVICE_URL=http://catalog-service:8888
      - ORDER_SERVICE_URL=http://order-service:8888
      - SHIP_SERVICE_URL=http://ship-service:8888
      - PAY_SERVICE_URL=http://pay-service:8888
      - COMMENT_RATE_SERVICE_URL=http://comment-rate-service:8888
      - RECOMMENDER_SERVICE_URL=http://recommender-ai-service:8888
    depends_on:
      - customer-service
      - book-service
      - cart-service
      - staff-service
      - manager-service
      - catalog-service
      - order-service
      - ship-service
      - pay-service
      - comment-rate-service
      - recommender-ai-service
