# version: "3.9"

services:
  customer-service:
    build: ./customer-service
    ports:
      - "8001:8000"
    environment:
      - CART_SERVICE_URL=http://cart-service:8000
    depends_on:
      - cart-service

  book-service:
    build: ./book-service
    ports:
      - "8002:8000"

  cart-service:
    build: ./cart-service
    ports:
      - "8003:8000"
    environment:
      - BOOK_SERVICE_URL=http://book-service:8000
    depends_on:
      - book-service

  staff-service:
    build: ./staff-service
    ports:
      - "8004:8000"

  manager-service:
    build: ./manager-service
    ports:
      - "8005:8000"

  catalog-service:
    build: ./catalog-service
    ports:
      - "8006:8000"

  order-service:
    build: ./order-service
    ports:
      - "8007:8000"
    environment:
      - PAY_SERVICE_URL=http://pay-service:8000
      - SHIP_SERVICE_URL=http://ship-service:8000
    depends_on:
      - pay-service
      - ship-service

  ship-service:
    build: ./ship-service
    ports:
      - "8008:8000"

  pay-service:
    build: ./pay-service
    ports:
      - "8009:8000"

  comment-rate-service:
    build: ./comment-rate-service
    ports:
      - "8010:8000"

  recommender-ai-service:
    build: ./recommender-ai-service
    ports:
      - "8011:8000"
    environment:
      - BOOK_SERVICE_URL=http://book-service:8000
      - COMMENT_RATE_SERVICE_URL=http://comment-rate-service:8000
    depends_on:
      - book-service
      - comment-rate-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer-service:8000
      - BOOK_SERVICE_URL=http://book-service:8000
      - CART_SERVICE_URL=http://cart-service:8000
      - STAFF_SERVICE_URL=http://staff-service:8000
      - MANAGER_SERVICE_URL=http://manager-service:8000
      - CATALOG_SERVICE_URL=http://catalog-service:8000
      - ORDER_SERVICE_URL=http://order-service:8000
      - SHIP_SERVICE_URL=http://ship-service:8000
      - PAY_SERVICE_URL=http://pay-service:8000
      - COMMENT_RATE_SERVICE_URL=http://comment-rate-service:8000
      - RECOMMENDER_SERVICE_URL=http://recommender-ai-service:8000
    depends_on:
      - customer-service
      - book-service
      - cart-service
      - staff-service
      - manager-service
      - catalog-service
      - order-service
      - ship-service
      - pay-service
      - comment-rate-service
      - recommender-ai-service
